version: '3.7'
services:
    db:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
    webserver:
        image: "jordanmarchetto/sw-books-server"
        ports:
            - "2222:2222"